name: Cross-Platform Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  VCPKG_COMMIT: '1318ab14aae14db20085441cd71366891a9c9d0c'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows MSVC",
            os: windows-latest,
            cc: "cl",
            cxx: "cl"
          }
          - {
            name: "macOS Clang",
            os: macos-latest,
            cc: "clang",
            cxx: "clang++"
          }
          - {
            name: "Ubuntu GCC",
            os: ubuntu-latest,
            cc: "gcc",
            cxx: "g++"
          }
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      # Windows-specific setup
      - name: Setup MSVC
        if: matrix.config.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Install vcpkg
        if: matrix.config.os == 'windows-latest'
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg integrate install

      - name: Cache vcpkg
        if: matrix.config.os == 'windows-latest'
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\AppData\Local\vcpkg
            C:\Users\runneradmin\.cache\vcpkg
          key: windows-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: windows-vcpkg-

      - name: Install Boost (Windows)
        if: matrix.config.os == 'windows-latest'
        run: |
          .\vcpkg\vcpkg install boost-test:x64-windows
          echo "VCPKG_ROOT=$env:GITHUB_WORKSPACE\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Append

      # macOS-specific setup
      - name: Install Boost (macOS)
        if: matrix.config.os == 'macos-latest'
        run: |
          brew update
          brew install boost
          echo "BOOST_ROOT=$(brew --prefix boost)" >> $GITHUB_ENV

      # Ubuntu-specific setup
      - name: Install Boost (Ubuntu)
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev
          echo "BOOST_ROOT=/usr" >> $GITHUB_ENV

      # Common build steps
      - name: Create Build Directory
        run: cmake -E make_directory ${{ github.workspace }}/build

      # Configure for each platform
      - name: Configure CMake (Windows)
        if: matrix.config.os == 'windows-latest'
        shell: pwsh
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake .. `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows `
            -A x64

      - name: Configure CMake (Unix)
        if: matrix.config.os != 'windows-latest'
        shell: bash
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake ${{ github.workspace }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
                -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
                -DBOOST_ROOT=${{ env.BOOST_ROOT }}

      # Build
      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config ${{ matrix.build_type }}

      # Test
      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure --verbose
